#Site Settings
name: GRAASCorp
title: GRAAS Corp
description: GRAAS Corp Website
url: "https://www.graascorp.com"
baseurl: ""
google_analytics:
font-awesome-include: true

#build settings
markdown: kramdown
exclude: ["README.md"]

#Material Jekyll Theme: http://alexcarpenter.github.io/material-jekyll-theme
fixedNav: 'true' # true or false
sass:
  style: compressed
